### ISSUE TITLE
Avoid crashing with native Bluetooth

### ISSUE THREAD

**Issue by Sensebellum** [fred-dev/Ps3EYE_multicam_syphon_gui_osc#3]
I have experienced this program crashing on my 2014 Macbook Pro running 10.9.4 when I connect bluetooth speakers to my computer. It will run for no longer than 15 seconds before crashing. This will happen if I connect before, during, or in between runtimes. This is not experienced with a mouse or any other bluetooth devices. I experienced this specifically with the UE BOOM bluetooth speakers: http://www.ultimateears.com/en-us/boom

I found the fix was to use a USB Bluetooth dongle. I used this one: http://www.amazon.com/gp/product/B005Z5HT2M/ref=oh_aui_detailpage_o02_s01?ie=UTF8&psc=1

However, you must force your Mac to use the dongle instead of the native port. I used this post to help me with that: http://www.atpeaz.com/index.php/2012/using-unsupported-bluetooth-4-0-usb-dongle-with-os-x/

Happy computing,

**Comment by fred-dev** [comment]
This app is depreciated and the repo will no longer be updated, please see https://github.com/fred-dev/ps3EyeSyphon_2 for the new version.
