### ISSUE TITLE
Does not accept other resolutions in mySettings.xml

### ISSUE THREAD

**Issue by CaseyJNova** [fred-dev/Ps3EYE_multicam_syphon_gui_osc#5]
I was working on getting this app to spit out frames that are 320 x 240 so that I could run OpenCV ont hem faster.

However, trying to change these in the settings files I had some trouble.

First, I noticed that the FRAMERATE tag does not respond to any values. I tried 30, 1, and null and that did not change the performance.

What I am really after is using a lower resolution. I know that 320x240 is acceptable for the PS3 Eye but I ended up getting some data glitch on the applications screen and no image through Syphon.

I am going to dig into the code and see what's up but I thought I would see if you knew anything.

```
    <CAMWIDTH>320</CAMWIDTH>
    <CAMHEIGHT>240</CAMHEIGHT>
```

```
    <FRAMERATE>25</FRAMERATE>
    <RECIEVEPORT>1234</RECIEVEPORT>
```

**Comment by fred-dev** [comment]
This app is depreciated and the repo will no longer be updated, please see https://github.com/fred-dev/ps3EyeSyphon_2 for the new version.
